- README.md
- src/main/resources/io/jenkins/plugins/echarts-common.jelly
- src/main/resources/io/jenkins/plugins/echarts-simple.jelly
Include alternative echarts versions, which provide smaller files but also fewer available graphs.
See [JENKINS-60770](https://issues.jenkins-ci.org/browse/JENKINS-60770) for more information.
> [JENKNIS-60770] provide alternative echars versions

- pom.xml
Push configuration of static analysis tools and all common test dependencies into a new [parent pom](https://github.com/jenkinsci/analysis-pom-plugin).
> Use common parent pom

- src/main/resources/charts/trend-chart.jelly
- src/main/resources/io/jenkins/plugins/echarts-common.jelly
- src/main/resources/io/jenkins/plugins/echarts-simple.jelly
- src/main/resources/io/jenkins/plugins/echarts.jelly
- src/main/webapp/js/echarts-scope.js
- src/main/webapp/js/pie-chart.js
- src/main/webapp/js/progress-chart.js
- src/main/webapp/js/trend-chart.js
- src/main/webapp/js/zoomable-trend-chart.js
Context: https://issues.jenkins-ci.org/browse/JENKINS-62625
> Move global JS methods to an ECharts API Object to avoid name clashes

- src/main/java/io/jenkins/plugins/echarts/BuildActionIterator.java
- src/test/java/io/jenkins/plugins/echarts/BuildActionIteratorTest.java
In the forensics plugin we might create several actions of the same type that show the repository statistics of different repositories. 
See https://github.com/jenkinsci/git-forensics-plugin/pull/213
> Make the selection of the build action configurable by callers

- .github/workflows/ci.yml
- pom.xml
See https://issues.jenkins.io/browse/JENKINS-65261 for details.
> [JENKINS-65261] Set echarts-build-trends library scope to provided

- src/main/webapp/js/configurable-trend-chart.js
- src/main/webapp/js/trend-chart.js
For most charts it makes sense to let the Y-Axis start at the chart minimum value and not at zero.
> Let y-axis of trend charts start at the minimum value and not at zero

- src/main/webapp/js/configurable-trend-chart.js
When we allow the whole chart to be clickable then the data zoom is not useful anymore.
> Only use an axis click to open results of selected build

- src/main/webapp/js/chart-configuration.js
I get that you don't want to not be able to use modern JS features, but I don't have time to re-write the junit tests to use ATH / something else.
Given how small this change is I suggest we just use `Object.assign` instead
ref https://github.com/jenkinsci/junit-plugin/pull/272#issuecomment-858123397
cc @uhafner
> Don't use spread

- src/main/webapp/js/configurable-trend-chart.js
Now the data zoom is skipped as clickable area. Only the chart will be allowed.
Basically the same as #150 but on the bottom of the chart.
> Fix click handling in data zoom at the bottom of chart

- src/main/webapp/js/configurable-trend-chart.js
Using a relative value makes not much sense.
> Use a gap of 40 pixels on top of the trend chart

- src/main/webapp/js/trend-chart.js
Replace `??` with `if-else`, see [JENKINS-66733](https://issues.jenkins.io/browse/JENKINS-66733). Nullish coalescing operator `??` is only supported since Google Chrome 80 or Firefox 72.
> [JENKINS-66733] Do not use `??` operator that is not supported by all browsers yet

- src/main/webapp/js/configurable-trend-chart.js
- src/main/webapp/js/trend-chart.js
Using rangeMin and rangeMax from chartModel instead of using 'dataMin' by default in yAxis in **configurable-trend-chart.js** and **trend-chart.js**.
I have already submitted an issue in the [echarts-build-trends](https://github.com/uhafner/echarts-build-trends/issues/206) repository. I have looked at this again more closely and find out, that the rangeMin and rangeMax property is ignored for the configurable trend charts. 
I tested the changes locally and using the following setup now:
```
/* Use 'dataMax' as range max.
model.setRangeMax(Math.max(
Math.max(createRangeMaxFor(dataSet, ReportSeriesBuilder.ACCURATE),
createRangeMaxFor(dataSet, ReportSeriesBuilder.MANUALLY)),
createRangeMaxFor(dataSet, ReportSeriesBuilder.INCORRECT)) + 10);
*/
// Use zero instead of 'dataMin' range min. …
```
> Use `rangeMin` and `rangeMax` in all charts if defined in model (instead of using `dataMin` by default)

- src/main/resources/io/jenkins/plugins/echarts-common.jelly
- src/main/resources/io/jenkins/plugins/echarts-simple.jelly
- src/main/resources/io/jenkins/plugins/echarts.jelly
- src/main/webapp/js/escapeMetaCharacters.js
- src/main/webapp/js/pie-chart.js
- src/main/webapp/js/progress-chart.js
Pie and Progress charts are not rendered if the chartDivId contains js meta characters like brackets:
[pie-chart.js](https://github.com/jenkinsci/echarts-api-plugin/blob/master/src/main/webapp/js/pie-chart.js) and [progress-chart.js](https://github.com/jenkinsci/echarts-api-plugin/blob/master/src/main/webapp/js/progress-chart.js) are using `jQuery3` to fetch the document element by id. All others use `document.getElementById()`.
Obviously the characters are not automatically escaped by jQuery. 
After escaping the characters, the charts are rendered:
> escape js meta characters if using jQuery3

- package-lock.json
- package.json
- pom.xml
- src/main/java/io/jenkins/plugins/echarts/ActionSelector.java
- src/main/java/io/jenkins/plugins/echarts/BuildActionIterator.java
- src/main/java/io/jenkins/plugins/echarts/GenericBuildActionIterator.java
- src/main/java/io/jenkins/plugins/echarts/TrendChartJobAction.java
> Add a generic iterator over build results

- pom.xml
The dependency is not required and all important consumers do not use the API anymore.
> Remove obsolete Eclipse collections dependency

- pom.xml
- src/test/java/io/jenkins/plugins/echarts/PackageArchitectureTest.java
- src/test/java/io/jenkins/plugins/echarts/PluginArchitectureTest.java
- src/test/resources/archunit_ignore_patterns.txt
- src/test/resources/design.puml
Since Java code will be added to these JS libraries as well it makes sense to enable the Java architecture tests.
> Enable architecture tests

- src/main/webapp/js/echarts-api.js
Toggling dark and light mode required a redrawing of all trend charts since the colors need to be adapted.
> Refresh trend charts when system dark mode settings fire an event

- src/main/resources/charts/chart-setup.jelly
Make sure label's `for` attribute matches input's `id` so that the browser understands they are connected (avoids accessibility warnings in Chrome dev tools)
Verified that Chrome warning is gone and clicking labels focuses inputs.
```[tasklist]
```
> Accessibility: labels should match input IDs

- src/main/resources/charts/chart-setup.jelly
- src/main/resources/io/jenkins/plugins/echarts/chart-setup-configure-chart.js
[JENKINS-73939](https://issues.jenkins.io/browse/JENKINS-73939)
Tested against warnings-ng's PMD and CheckStyle.
https://www.loom.com/share/b6ee2a0732ce43e2af21ed5a6718a4ff?sid=1339b3bf-4076-4f88-91be-b5f22e316314
https://www.loom.com/share/ac5e2d4439374506b76ad9a8e85bac69?sid=6e1ca5df-dfc8-44c2-9f22-27c984be634d
> [JENKINS-73939] Un-inline JavaScript in chart-setup.jelly

- src/main/resources/charts/trend-setup.jelly
Two of the input fields had a label with broken ID.
> Add suffix for missing IDs in label of input fields

- src/main/resources/charts/chart-setup.jelly
- src/main/resources/charts/trend-setup.jelly
See [JENKINS-66384](https://issues.jenkins.io/browse/JENKINS-66384).
Changed the minimum allowed value for "Maximum number of builds to consider" to 1 (from 2) such that it allows inputs less than 2. In that case all the builds will be considered.
> [JENKINS-66384] Fix minimum number of builds validation 

- package.json
- pom.xml
- src/main/resources/io/jenkins/plugins/echarts.jelly
- src/main/webapp/js/echarts-api.js
ECharts does not support `oklch` yet. So we need to replace all Jenkins colors by plain RGB HEX values before setting the chart options.
See [JENKINS-75242](https://issues.jenkins.io/browse/JENKINS-75242).
Supersedes #380
> Convert `oklch` colors to HEX values

- package.json
- pom.xml
- src/main/resources/io/jenkins/plugins/echarts.jelly
- src/main/webapp/js/echarts-api.js
This is a much better fix for [JENKINS-75242](https://issues.jenkins.io/browse/JENKINS-75242), see discussion in https://github.com/apache/echarts/issues/20757.
This PR basically replaces https://github.com/jenkinsci/echarts-api-plugin/pull/383
> Use `{color: inherit}` for emphasis

- pom.xml
- src/main/webapp/js/echarts-api.js
Line charts should disable the emphasis, it makes no sense there.
> Add a special case for emphasis in line charts

- src/main/webapp/js/echarts-api.js
This PR introduces the following changes when users click on the build numbers/coordinates in the trend chart : 
- cmd/ctrl+click - Opens the build's static result on a new tab while keeping the current tab in focus.
- shift+click - Opens the build's static result on a new window and shifts focus to the new window.
See [JENKINS-64581](https://issues.jenkins.io/browse/JENKINS-64581).
Tested this feature on: 
Jenkins 2.505
Warnings Plugin 12.5.0
macOS 10.15.7
Chrome 135.0.0.0
> Improve Trend Chart navigation behaviour 

- pom.xml
- src/test/java/io/jenkins/plugins/archunit/PluginArchitectureTest.java
Bump the version of plugin-util to 6.1165.v322e76215b_a_4. This version contains the missing class again.
> [JENKINS-76020] Resolve missing architecture rules
